# Generated by Django 3.2.4 on 2021-07-05 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thing',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
