# Generated by Django 3.2.4 on 2021-07-06 08:17

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20210705_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(default='things/default.jpeg', upload_to=things.models.upload_to, verbose_name='Image'),
        ),
    ]
