# Generated by Django 3.2.4 on 2021-07-08 07:06

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_thing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.FileField(default='things/default.jpeg', upload_to=things.models.upload_to, verbose_name='Image'),
        ),
    ]
